### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by ramtinmass** [mirjaj/grupparbete#17]
- [x] Use more pull requests and branching! (Currently only one).

- [x]  Extend the description to contain installation instructions and an explanation of how to play the game.

- [x] Add some pictures of the graphical user interface, there are no current examples for anyone to see.

- [x] Use labels to label issues, especially for bugs.

Good commit messages!
Good use of features and milestones. We are very proud of you.

Ramtin et al.

**Comment by aughak** [comment]
I think we have completed the points we got on our review. Great review overall! Lovely.
