### ISSUE TITLE
Komplettering - Can't run the game!

### ISSUE THREAD

**Issue by slarse** [mirjaj/grupparbete#29]
Hey!

The java files in the top directory do not compile at all. The ones in the `Geni` directory do, but upon running the main method I get a `FileNotFoundException` on `white_dice.png`. I want you to do the following:

- [x] Make sure there is only **one set** of source files in the master branch. As it stands, I don't know which I should try to run.
- [x] Make sure all resources are in in the correct place in the master branch, so that it can be cloned, compiled and run without issues.

**Comment by mirjaj** [comment]
Done! You can now run the program from the src folder, and should not have any issues with the pictures!

**Comment by slarse** [comment]
Indeed I can! Will open a new issue when I've corrected everything else.
