### ISSUE TITLE
Pass - Great job!

### ISSUE THREAD

**Issue by slarse** [mirjaj/grupparbete#30]
First of all, let me say that I think you've done a really good job with this. The idea for the game is good to begin with, and the end product is quite nice. You even took the time to add a menu and different difficulties! Anyhow, my feedback here will cover the project as a whole, and I will not go into specifics on your code.

### Stuff that could be improved
* **Testing:** Documented testing is probably the weakest part of your project. You may come with an objection along the lines of "but hey, this code is difficult to test!". The thing is though, we should attempt to write code that is _easy_ to test. If it's difficult to test, the design may need to be reworked! Granted, testing the graphical interface with automated tests is actually quite difficult, but one should always strive to separate the program's business logic (in your case, the _game logic_) from the interface in such a way to make the business logic testable.
* **Commit messages:** vary quite a lot both in terms of content and tense. For example, some commit messages are in present tense on the imperative form, such as `Delete Player.java`, others in past tense such as `Added images that are used in the main class`, and yet others that just describe an ongoing action, like `working on game structure`. It's quite important to try to keep commit messages consistent, both in terms of their contents and the grammatical constructs the consist of. An example of very strict commit rules can be found in the [Angular.js project](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) (not at all saying this is the de-facto way of doing it, I sure don't, it's just an example of structured commit messages!).
* **Commit messages can also:** refer to the issues that they are related to. This gives context to a commit, for example _why_ it is needed in the first place. It also has the added benefit of making it easy to track progress from within the issue tracker.
**Some things about the game are not super clear:** For example, I have no idea of which piece I play as, or where I'm going. There is also very little feedback to answering questions (other tha the score increasing or not).
* **You should not use the default package:** That is to say, you should declare a package in the Java source files. To be able to differentiate packages from different projects, it's common to have the reverse of the organization domain name prepended to the package name. For example, an inda project could have `se.kth.inda` prepended. Then, for example, the main class and any closely associated classes could go into `se.kth.inda.main`, and utility classes into `se.kth.inda.util`. Note that there must be an accompanying directory structure, with the dots replaced by slashes, e.g. `se/kth/inda/util`, and this directory structure would then normally be placed in the `src` directory.

### Stuff you did good!
* **Nice description:** The README in the top directory is really nice and fleshed out. The Gameboard UI doesn't seem to reflect the final version though :). Anyway, this is the first thing any visitor to the repo sees, so having a good description is actually more important than you'd initially think. Say you're working with an open source project, and want people to get interesting, then that first impression is essential! Also, people tend to really like pictures, so I would put them closer to the top!
* **Delivered a solid final product:** You went well beyond your MVP what with a menu, NPCs and even different difficulty levels. Awesome!
* **Work seems to be well distributed:** Judging by your commit history, it seems like everyone has taken their fair share of responsibility in the project. This is probably one of the most difficult parts, and especially so when there are three of you, instead of two.
* **Nice interface:** I quite like the interface you built. Disregarding the not-so-clear elements, I think it's intuitive to use and looks quite nice.

That's it for the feedback, I think you did a really good job overall. Well done, you've passed DD1349!

**Comment by aughak** [comment]
I must say that I found this course to be exceedingly likeable and also highly useful. I think we co-operated very well working on different parts of the project and then meeting up every now and then so that we could set different classes together. 

I think the hardest aspect of this project has been managing Git. Also it was perhaps a bit stale at the beginning when we did not know what to do, but once we got our ideas together it started rolling and the end result was presentable indeed.

A shame really that I could not attend the last session of the course (and the year), due to my work interview. I would personally much rather have been on this last session than at some boring interview, that being said I did get the job so it was not in vain.

On a sidenote I think you have been utterly splendid as an assistent in these courses and I highly recommend that you enlist next year again, if you do have the time to do so.

**Comment by slarse** [comment]
@aughak I'm glad you think so! This course, along with pretty much any project, is more or less what you make of it. Put some effort into it and you usually end up feeling it was worth it, and learn a great deal.

git takes years to master. I'm good with git, but nowhere near knowing it by heart. If you wanna dive real deep, I've heard good things about _Pro Git_ by Scott Chacon and Ben Straub, [available for free on the interwebz](https://git-scm.com/book/en/v2). I haven't read it myself, mind you, so I can only go on public opinion there.

Thanks, that means a lot, I will be rejoining the ranks next year :)

Best of luck to all of you guys!
